import { Animal } from './AdjectiveAnimalGenerator.tsx'

export const animals: Animal[] = [
    {emoji:'🐵', name:'Monkey'},
    {emoji:'🐒', name:'Monkey'},
    {emoji:'🦍', name:'Gorilla'},
    {emoji:'🦧', name:'Orangutan'},
    {emoji:'🐶', name:'Dog'},
    {emoji:'🐕', name:'Dog'},
    {emoji:'🦮', name:'Dog'},
    {emoji:'🐕‍🦺', name:'Dog'},
    {emoji:'🐩', name:'Poodle'},
    {emoji:'🐺', name:'Wolf'},
    {emoji:'🦊', name:'Fox'},
    {emoji:'🦝', name:'Raccoon'},
    {emoji:'🐱', name:'Cat'},
    {emoji:'🐈', name:'Cat'},
    {emoji:'🐈‍⬛', name:'Cat'},
    {emoji:'🦁', name:'Lion'},
    {emoji:'🐯', name:'Tiger'},
    {emoji:'🐅', name:'Tiger'},
    {emoji:'🐆', name:'Leopard'},
    {emoji:'🐴', name:'Horse'},
    {emoji:'🫎', name:'Moose'},
    {emoji:'🫏', name:'Donkey'},
    {emoji:'🐎', name:'Horse'},
    {emoji:'🦄', name:'Unicorn'},
    {emoji:'🦓', name:'Zebra'},
    {emoji:'🦌', name:'Deer'},
    {emoji:'🦬', name:'Bison'},
    {emoji:'🐮', name:'Cow'},
    {emoji:'🐂', name:'Ox'},
    {emoji:'🐃', name:'Buffalo'},
    {emoji:'🐄', name:'Cow'},
    {emoji:'🐷', name:'Pig'},
    {emoji:'🐖', name:'Pig'},
    {emoji:'🐗', name:'Boar'},
    {emoji:'🐽', name:'Pig'},
    {emoji:'🐏', name:'Ram'},
    {emoji:'🐑', name:'Ewe'},
    {emoji:'🐐', name:'Goat'},
    {emoji:'🐪', name:'Camel'},
    {emoji:'🐫', name:'Camel'},
    {emoji:'🦙', name:'Llama'},
    {emoji:'🦒', name:'Giraffe'},
    {emoji:'🐘', name:'Elephant'},
    {emoji:'🦣', name:'Mammoth'},
    {emoji:'🦏', name:'Rhinoceros'},
    {emoji:'🦛', name:'Hippopotamus'},
    {emoji:'🐭', name:'Mouse'},
    {emoji:'🐁', name:'Mouse'},
    {emoji:'🐀', name:'Rat'},
    {emoji:'🐹', name:'Hamster'},
    {emoji:'🐰', name:'Rabbit'},
    {emoji:'🐇', name:'Rabbit'},
    {emoji:'🐿️', name:'Chipmunk'},
    {emoji:'🦫', name:'Beaver'},
    {emoji:'🦔', name:'Hedgehog'},
    {emoji:'🦇', name:'Bat'},
    {emoji:'🐻', name:'Bear'},
    {emoji:'🐻‍❄️', name:'PolarBear'},
    {emoji:'🐨', name:'Koala'},
    {emoji:'🐼', name:'Panda'},
    {emoji:'🦥', name:'Sloth'},
    {emoji:'🦦', name:'Otter'},
    {emoji:'🦨', name:'Skunk'},
    {emoji:'🦘', name:'Kangaroo'},
    {emoji:'🦡', name:'Badger'},
    {emoji:'🦃', name:'Turkey'},
    {emoji:'🐔', name:'Chicken'},
    {emoji:'🐓', name:'Rooster'},
    {emoji:'🐣', name:'Chick'},
    {emoji:'🐤', name:'Chick'},
    {emoji:'🐥', name:'Chick'},
    {emoji:'🐦', name:'Bird'},
    {emoji:'🐧', name:'Penguin'},
    {emoji:'🕊️', name:'Dove'},
    {emoji:'🦅', name:'Eagle'},
    {emoji:'🦆', name:'Duck'},
    {emoji:'🦢', name:'Swan'},
    {emoji:'🦉', name:'Owl'},
    {emoji:'🦤', name:'Dodo'},
    {emoji:'🪶', name:'Feather'},
    {emoji:'🦩', name:'Flamingo'},
    {emoji:'🦚', name:'Peacock'},
    {emoji:'🦜', name:'Parrot'},
    {emoji:'🪽', name:'Wing'},
    {emoji:'🐦‍⬛', name:'Bird'},
    {emoji:'🪿', name:'Goose'},
    {emoji:'🐸', name:'Frog'},
    {emoji:'🐊', name:'Crocodile'},
    {emoji:'🐢', name:'Turtle'},
    {emoji:'🦎', name:'Lizard'},
    {emoji:'🐍', name:'Snake'},
    {emoji:'🐲', name:'Dragon'},
    {emoji:'🐉', name:'Dragon'},
    {emoji:'🦕', name:'Sauropod'},
    {emoji:'🦖', name:'T-Rex'},
    {emoji:'🐳', name:'Whale'},
    {emoji:'🐋', name:'Whale'},
    {emoji:'🐬', name:'Dolphin'},
    {emoji:'🦭', name:'Seal'},
    {emoji:'🐟', name:'Fish'},
    {emoji:'🐠', name:'Fish'},
    {emoji:'🐡', name:'Blowfish'},
    {emoji:'🦈', name:'Shark'},
    {emoji:'🐙', name:'Octopus'},
    {emoji:'🐚', name:'Shell'},
    {emoji:'🪸', name:'Coral'},
    {emoji:'🪼', name:'Jellyfish'},
    {emoji:'🦀', name:'Crab'},
    {emoji:'🦞', name:'Lobster'},
    {emoji:'🦐', name:'Shrimp'},
    {emoji:'🦑', name:'Squid'},
    {emoji:'🦪', name:'Oyster'},
    {emoji:'🐌', name:'Snail'},
    {emoji:'🦋', name:'Butterfly'},
    {emoji:'🐛', name:'Bug'},
    {emoji:'🐜', name:'Ant'},
    {emoji:'🐝', name:'Honeybee'},
    {emoji:'🪲', name:'Beetle'},
    {emoji:'🐞', name:'Lady Beetle'},
    {emoji:'🦗', name:'Cricket'},
    {emoji:'🪳', name:'Cockroach'},
    {emoji:'🕷️', name:'Spider'},
    {emoji:'🕸️', name:'Spider Web'},
    {emoji:'🦂', name:'Scorpion'},
    {emoji:'🦟', name:'Mosquito'},
    {emoji:'🪰', name:'Fly'},
    {emoji:'🪱', name:'Worm'},
    {emoji:'🦠', name:'Microbe'},
]

export const adjectives : string[] = [
    'adorable',
    'adventurous',
    'aggressive',
    'agreeable',
    'alert',
    'alive',
    'amused',
    'angry',
    'annoyed',
    'annoying',
    'anxious',
    'arrogant',
    'ashamed',
    'attractive',
    'average',
    'awful',
    'bad',
    'beautiful',
    'better',
    'bewildered',
    'black',
    'bloody',
    'blue',
    'blue-eyed',
    'blushing',
    'bored',
    'brainy',
    'brave',
    'breakable',
    'bright',
    'busy',
    'calm',
    'careful',
    'cautious',
    'charming',
    'cheerful',
    'clean',
    'clear',
    'clever',
    'cloudy',
    'clumsy',
    'colorful',
    'combative',
    'comfortable',
    'concerned',
    'condemned',
    'confused',
    'cooperative',
    'courageous',
    'crazy',
    'creepy',
    'crowded',
    'cruel',
    'curious',
    'cute',
    'dangerous',
    'dark',
    'dead',
    'defeated',
    'defiant',
    'delightful',
    'depressed',
    'determined',
    'different',
    'difficult',
    'disgusted',
    'distinct',
    'disturbed',
    'dizzy',
    'doubtful',
    'drab',
    'dull',
    'eager',
    'easy',
    'elated',
    'elegant',
    'embarrassed',
    'enchanting',
    'encouraging',
    'energetic',
    'enthusiastic',
    'envious',
    'evil',
    'excited',
    'expensive',
    'exuberant',
    'fair',
    'faithful',
    'famous',
    'fancy',
    'fantastic',
    'fierce',
    'filthy',
    'fine',
    'foolish',
    'fragile',
    'frail',
    'frantic',
    'friendly',
    'frightened',
    'funny',
    'gentle',
    'gifted',
    'glamorous',
    'gleaming',
    'glorious',
    'good',
    'gorgeous',
    'graceful',
    'grieving',
    'grotesque',
    'grumpy',
    'handsome',
    'happy',
    'healthy',
    'helpful',
    'helpless',
    'hilarious',
    'homeless',
    'homely',
    'horrible',
    'hungry',
    'hurt',
    'ill',
    'important',
    'impossible',
    'inexpensive',
    'innocent',
    'inquisitive',
    'itchy',
    'jealous',
    'jittery',
    'jolly',
    'joyous',
    'kind',
    'lazy',
    'light',
    'lively',
    'lonely',
    'long',
    'lovely',
    'lucky',
    'magnificent',
    'misty',
    'modern',
    'motionless',
    'muddy',
    'mushy',
    'mysterious',
    'nasty',
    'naughty',
    'nervous',
    'nice',
    'nutty',
    'obedient',
    'obnoxious',
    'odd',
    'old-fashioned',
    'open',
    'outrageous',
    'outstanding',
    'panicky',
    'perfect',
    'plain',
    'pleasant',
    'poised',
    'poor',
    'powerful',
    'precious',
    'prickly',
    'proud',
    'putrid',
    'puzzled',
    'quaint',
    'real',
    'relieved',
    'repulsive',
    'rich',
    'scary',
    'selfish',
    'shiny',
    'shy',
    'silly',
    'sleepy',
    'smiling',
    'smoggy',
    'sore',
    'sparkling',
    'splendid',
    'spotless',
    'stormy',
    'strange',
    'stupid',
    'successful',
    'super',
    'talented',
    'tame',
    'tasty',
    'tender',
    'tense',
    'terrible',
    'thankful',
    'thoughtful',
    'thoughtless',
    'tired',
    'tough',
    'troubled',
    'ugliest',
    'ugly',
    'uninterested',
    'unsightly',
    'unusual',
    'upset',
    'uptight',
    'vast',
    'victorious',
    'vivacious',
    'wandering',
    'weary',
    'wicked',
    'wide-eyed',
    'wild',
    'witty',
    'worried',
    'worrisome',
    'wrong',
    'zany',
    'zealous',
]
